name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version-string }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Calculate semantic version
        id: versioning
        uses: bitshifted/git-auto-semver@v1.1.0
        with:
          main_branch: main
          create_tag: true
          tag_prefix: 'v'

  publish:
    name: Publish to Hex.pm
    needs: version
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.4'
          otp-version: '25.3'
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
